export enum ErrorsDescriptions {
    NO_REFRESH_TOKEN_ERROR = 'NO_REFRESH_TOKEN_ERROR',
    TOKEN_EXCHANGE_ERROR = 'TOKEN_EXCHANGE_ERROR',
    LOGOUT_ALL_ERROR = 'LOGOUT_ALL_ERROR',
    LOGOUT_ERROR = 'LOGOUT_ERROR',
    REFRESH_TOKEN_PROBLEM = 'REFRESH_TOKEN_PROBLEM',
    SIGNIN_ERROR = 'SIGNIN_ERROR',
    SIGNUP_ERROR = 'SIGNUP_ERROR',
    NO_GOOGLE_CODE_ERROR = 'NO_GOOGLE_CODE_ERROR'
}
