export enum ErrorsDescriptions {
    NO_REFRESH_TOKEN_ERROR = 'NO_REFRESH_TOKEN_ERROR',
    TOKEN_EXCHANGE_ERROR = 'TOKEN_EXCHANGE_ERROR',
    LOGOUT_ALL_ERROR = 'LOGOUT_ALL_ERROR',
    LOGOUT_ERROR = 'LOGOUT_ERROR',
    REFRESH_TOKEN_PROBLEM = 'REFRESH_TOKEN_PROBLEM',
    SIGNIN_ERROR = 'SIGNIN_ERROR',
    SIGNUP_ERROR = 'SIGNUP_ERROR',
    NO_GOOGLE_CODE_ERROR = 'NO_GOOGLE_CODE_ERROR',
    GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR',
    CHANGE_USER_IMAGE_ERROR = 'CHANGE_USER_IMAGE_ERROR',
    CHANGE_USER_INFO_ERROR = 'CHANGE_USER_INFO_ERROR',
    UPLOAD_IMAGE_URL_ERROR = 'UPLOAD_IMAGE_URL_ERROR',
    TOKEN_PROVIDED_ERROR = 'TOKEN_PROVIDED_ERROR'
}
